apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: serverhttp
  labels:
    app: serverhttp
spec:
  selector:
    matchLabels:
      app: serverhttp
  replicas: 5
  template:
    metadata:
      labels:
        app: "serverhttp"
    spec:
      containers:
      - name: serverhttp
        image: pacalexandre/server-http:0.0.1
        ports:
        - containerPort: 8080